### ISSUE TITLE
This tutorial do not help me with problem bouncy castle provider

### ISSUE THREAD

**Issue by wwwAiru** [kriegaex/JarClassLoader#2] opened 2022-08-31 14:03 UTC
Hi i have a problem with bouncy castle provider in jar. I edit my pom file, to add dependency custom jarclassloader. But problem not gone.

**Comment by kriegaex** [comment] 2022-08-31 14:55
Please help me to help you by explaining your problem:

1. Please edit the subject. "Help me, please" does not qualify as a problem summary.
2. Please also edit the description. An example project is great, but you did not mention what your problem is and did not show me what you tried. I cannot find any trace of this tool in your Maven POM.

Thank you very much.

**Comment by wwwAiru** [comment] 2022-08-31 16:20
Can you share for me example proj with custom class loader? I have no experience for understanding your guide. Sorry(

**Comment by wwwAiru** [comment] 2022-09-01 08:41
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.example.application</groupId>
    <artifactId>hilla-push-notifications</artifactId>
    <name>hilla-push-notifications</name>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <java.version>17</java.version>
        <hilla.version>1.0.8</hilla.version>
        <jar-class-loader.version>1.0</jar-class-loader.version>
        <one-jar-main-class>com.example.application.Application</one-jar-main-class>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
    </parent>

    <repositories>
        

        
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
        </repository>
        
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        
        <pluginRepository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <url>
                https://maven.vaadin.com/vaadin-prereleases/
            </url>
        </pluginRepository>
    </pluginRepositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.hilla</groupId>
                <artifactId>hilla-bom</artifactId>
                <version>${hilla.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>de.scrum-master</groupId>
            <artifactId>jar-class-loader</artifactId>
            <version>${jar-class-loader.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.hilla</groupId>
            <artifactId>hilla</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.hilla</groupId>
            <artifactId>hilla-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.16.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.martijndwars</groupId>
            <artifactId>web-push</artifactId>
            <version>5.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-testbench</artifactId>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.0.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                
                <configuration>
                    <wait>500</wait>
                    <maxAttempts>240</maxAttempts>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>dev.hilla</groupId>
                <artifactId>hilla-maven-plugin</artifactId>
                <version>${hilla.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            
            <id>production</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>dev.hilla</groupId>
                        <artifactId>hilla-maven-plugin</artifactId>
                        <version>${hilla.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                                <phase>compile</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <productionMode>true</productionMode>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>it</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.8.1</version>
                        <configuration>
                            <source>${java.version}</source>
                            <target>${java.version}</target>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.3.0</version>
                        <executions>
                            <execution>
                                <id>copy</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>copy-dependencies</goal>
                                </goals>
                                <configuration>
                                    
                                    <excludeArtifactIds>jar-class-loader,junit</excludeArtifactIds>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>unpack-jar-class-loader</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>unpack</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                    
                                    <artifact>de.scrum-master:jar-class-loader:${jar-class-loader.version}</artifact>
                                    <includes>**/*.class</includes>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.2.2</version>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>${one-jar-main-class}</mainClass>
                                    <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                </manifest>
                            </archive>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>

    </profiles>
</project>

**Comment by wwwAiru** [comment] 2022-09-01 09:42
No luck. Bouncy castle provider not work.  java.security.InvalidKeyException: Not an EC key: ECDH
        at jdk.crypto.ec/sun.security.ec.ECKeyFactory.checkKey(ECKeyFactory.java:122)

**Comment by kriegaex** [comment] 2022-09-03 14:30
Why did you delete the link to your sample project? And why are you posting anb incomplete POM without any code instead? Do you want to make it extra hard to reproduce your problem?

Besides, your latest error message looks as if indeed some crypto functionality is being called and you simply have a problem with your key or keystore. I am closing this question as invalid, because you are not cooperating. If I cannot reproduce your problem, how do you expect me to help you? We can re-open the question, if you finally give me what I need: a full, but minimal reproducer project.

One more hint: You seem to use Spring Boot, which has its own fat JAR classloader. That one might conflict with the one in this library here.

With regard to your changed subject line "This tutorial do not help me with problem bouncy castle provider": This still does not qualify as a problem summary, because it does not explain which problem you have. It is just a general complaint. By the way, this repository provides a **tool library**, not a **tutorial**. I would be glad to try to help, but only if I can reproduce the problem. You do your job first - enabling me to help you - then I can volunteer to help. I need a project showing that

* your BouncyCastle stuff actually works outside of the fat JAR
* and how exactly you are trying to package and start the fat JAR subsequently.

**Closed as completed by kriegaex** 2022-09-03 14:30 UTC
Labels: invalid, question
